Post {{baseUrl}}/auth
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###

Post {{baseUrl}}/auth/me
Content-Type: application/json
{{authorization-header}}

###

Get {{baseUrl}}/auth/oauth/google