Post {{baseUrl}}/budgets
Content-Type: application/json
{{authorization-header}}

{
  "maxAmount": 2000,
  "theme": "red",
  "category": "entertainment"
}

###

Get {{baseUrl}}/budgets
Content-Type: application/json
{{authorization-header}}


