export enum Color {
  // Secondary Colors
  RED = "RED",
  CYAN = "CYAN",
  NAVY = "NAVY",
  GREEN = "GREEN",
  YELLOW = "YELLOW",
  SECONDARY_PURPLE = "SECONDARY_PURPLE",

  // Other Colors
  BLUE = "BLUE",
  GOLD = "GOLD",
  BROWN = "BROWN",
  ORANGE = "ORANGE",
  MARGENTO = "MARGENTO",
  NAVY_GRAY = "NAVY_GRAY",
  OTHER_PURPLE = "OTHER_PURPLE",
  TURQUOISE = "TURQUOISE",
  ARMY_GREEN = "ARMY_GREEN",
}
