import { Injectable } from "@nestjs/common";
import { generatePdfFromHtml, generatePdfFromSection } from "./utils/generate-pdf";

@Injectable()
export class PdfService {
  async generateSamplePdf() {
    // const filename = await generatePdfFromHtml(html, "sample");
    const filename = await generatePdfFromSection(
      "http://localhost:3000/portal/courses/pdf/courses",
      "#courses-grid",
      "justice-courses",
    );

    const pdfUrl = `http://localhost:3001/public/pdfs/${filename}`; // This is the public URL

    return { url: pdfUrl };
  }
}

// Example usage
const html = `
  <!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>TypeScript PDF Example</title>
    <style>
      body { font-family: sans-serif; padding: 20px; }
      h1 { color: #2c3e50; text-align: center; }
      .container { border: 1px solid #ddd; padding: 15px; border-radius: 8px; }
    </style>
  </head>
  <body>
    <div class="container">
      <h1>Hello from TypeScript!</h1>
      <p>This PDF was generated by a server-side TypeScript application using Puppeteer.</p>
      <ul>
        <li>Type safety</li>
        <li>Improved developer experience</li>
        <li>Scalable and maintainable code</li>
      </ul>
    </div>
  </body>
  </html>
`;
